project:
  type: website
  output-dir: docs

website:
  title: "Shoon's Data Science Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About

